name: build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: 8
          cache: 'gradle'

      - name: Build and test
        run: ./gradlew --continue check

      - name: Publish JUnit Report
        uses: mikepenz/action-junit-report@v2.8.1
        if: always()
        with:
          report_paths: '**/build/test-results/test/TEST-*.xml'
